// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoExRate.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AverageRateResponse
    {
        /// <summary>
        /// Initializes a new instance of the AverageRateResponse class.
        /// </summary>
        public AverageRateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AverageRateResponse class.
        /// </summary>
        public AverageRateResponse(string pair = default(string), double? averageRate = default(double?), IList<RateResponse> rates = default(IList<RateResponse>))
        {
            Pair = pair;
            AverageRate = averageRate;
            Rates = rates;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Pair")]
        public string Pair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AverageRate")]
        public double? AverageRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Rates")]
        public IList<RateResponse> Rates { get; set; }

    }
}
