// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoExRate.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Market.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Market
    {
        [EnumMember(Value = "Lykke")]
        Lykke,
        [EnumMember(Value = "Kraken")]
        Kraken,
        [EnumMember(Value = "Bitfinex")]
        Bitfinex
    }
    internal static class MarketEnumExtension
    {
        internal static string ToSerializedValue(this Market? value)
        {
            return value == null ? null : ((Market)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Market value)
        {
            switch( value )
            {
                case Market.Lykke:
                    return "Lykke";
                case Market.Kraken:
                    return "Kraken";
                case Market.Bitfinex:
                    return "Bitfinex";
            }
            return null;
        }

        internal static Market? ParseMarket(this string value)
        {
            switch( value )
            {
                case "Lykke":
                    return Market.Lykke;
                case "Kraken":
                    return Market.Kraken;
                case "Bitfinex":
                    return Market.Bitfinex;
            }
            return null;
        }
    }
}
