// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoExRate.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Pair.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Pair
    {
        [EnumMember(Value = "BTCUSD")]
        BTCUSD,
        [EnumMember(Value = "ETHUSD")]
        ETHUSD
    }
    internal static class PairEnumExtension
    {
        internal static string ToSerializedValue(this Pair? value)
        {
            return value == null ? null : ((Pair)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Pair value)
        {
            switch( value )
            {
                case Pair.BTCUSD:
                    return "BTCUSD";
                case Pair.ETHUSD:
                    return "ETHUSD";
            }
            return null;
        }

        internal static Pair? ParsePair(this string value)
        {
            switch( value )
            {
                case "BTCUSD":
                    return Pair.BTCUSD;
                case "ETHUSD":
                    return Pair.ETHUSD;
            }
            return null;
        }
    }
}
