// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoExRate.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RateResponse
    {
        /// <summary>
        /// Initializes a new instance of the RateResponse class.
        /// </summary>
        public RateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RateResponse class.
        /// </summary>
        public RateResponse(string market = default(string), string pair = default(string), double? rate = default(double?), System.DateTime? createdUtc = default(System.DateTime?))
        {
            Market = market;
            Pair = pair;
            Rate = rate;
            CreatedUtc = createdUtc;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Market")]
        public string Market { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Pair")]
        public string Pair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Rate")]
        public double? Rate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedUtc")]
        public System.DateTime? CreatedUtc { get; set; }

    }
}
